//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstoqueCliente1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstoqueData", Namespace="http://schemas.datacontract.org/2004/07/Estoques")]
    [System.SerializableAttribute()]
    public partial class EstoqueData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstoqueProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroProdutoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoProduto {
            get {
                return this.DescricaoProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoProdutoField, value) != true)) {
                    this.DescricaoProdutoField = value;
                    this.RaisePropertyChanged("DescricaoProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstoqueProduto {
            get {
                return this.EstoqueProdutoField;
            }
            set {
                if ((this.EstoqueProdutoField.Equals(value) != true)) {
                    this.EstoqueProdutoField = value;
                    this.RaisePropertyChanged("EstoqueProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProduto {
            get {
                return this.NomeProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeProdutoField, value) != true)) {
                    this.NomeProdutoField = value;
                    this.RaisePropertyChanged("NomeProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroProduto {
            get {
                return this.NumeroProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroProdutoField, value) != true)) {
                    this.NumeroProdutoField = value;
                    this.RaisePropertyChanged("NumeroProduto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://projetoavaliativo.dm113/02", ConfigurationName="ServiceReference1.IEstoqueServiceV2")]
    public interface IEstoqueServiceV2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/AdicionarQtdeProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/AdicionarQtdeProdutoEstoqueRe" +
            "sponse")]
        bool AdicionarQtdeProdutoEstoque(string NumeroProdutoEstoque, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/AdicionarQtdeProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/AdicionarQtdeProdutoEstoqueRe" +
            "sponse")]
        System.Threading.Tasks.Task<bool> AdicionarQtdeProdutoEstoqueAsync(string NumeroProdutoEstoque, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/RemoverQtdeProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/RemoverQtdeProdutoEstoqueResp" +
            "onse")]
        bool RemoverQtdeProdutoEstoque(string NumeroProdutoEstoque, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/RemoverQtdeProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/RemoverQtdeProdutoEstoqueResp" +
            "onse")]
        System.Threading.Tasks.Task<bool> RemoverQtdeProdutoEstoqueAsync(string NumeroProdutoEstoque, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/ConsultarEstoqueResponse")]
        int ConsultarEstoque(string NumeroProdutoEstoque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IEstoqueServiceV2/ConsultarEstoqueResponse")]
        System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string NumeroProdutoEstoque);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstoqueServiceV2Channel : EstoqueCliente1.ServiceReference1.IEstoqueServiceV2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstoqueServiceV2Client : System.ServiceModel.ClientBase<EstoqueCliente1.ServiceReference1.IEstoqueServiceV2>, EstoqueCliente1.ServiceReference1.IEstoqueServiceV2 {
        
        public EstoqueServiceV2Client() {
        }
        
        public EstoqueServiceV2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstoqueServiceV2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstoqueServiceV2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstoqueServiceV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AdicionarQtdeProdutoEstoque(string NumeroProdutoEstoque, int Quantidade) {
            return base.Channel.AdicionarQtdeProdutoEstoque(NumeroProdutoEstoque, Quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> AdicionarQtdeProdutoEstoqueAsync(string NumeroProdutoEstoque, int Quantidade) {
            return base.Channel.AdicionarQtdeProdutoEstoqueAsync(NumeroProdutoEstoque, Quantidade);
        }
        
        public bool RemoverQtdeProdutoEstoque(string NumeroProdutoEstoque, int Quantidade) {
            return base.Channel.RemoverQtdeProdutoEstoque(NumeroProdutoEstoque, Quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverQtdeProdutoEstoqueAsync(string NumeroProdutoEstoque, int Quantidade) {
            return base.Channel.RemoverQtdeProdutoEstoqueAsync(NumeroProdutoEstoque, Quantidade);
        }
        
        public int ConsultarEstoque(string NumeroProdutoEstoque) {
            return base.Channel.ConsultarEstoque(NumeroProdutoEstoque);
        }
        
        public System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string NumeroProdutoEstoque) {
            return base.Channel.ConsultarEstoqueAsync(NumeroProdutoEstoque);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://projetoavaliativo.dm113/01", ConfigurationName="ServiceReference1.IEstoqueService")]
    public interface IEstoqueService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/ListarProdutosEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/ListarProdutosEstoqueResponse")]
        EstoqueCliente1.ServiceReference1.EstoqueData[] ListarProdutosEstoque();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/ListarProdutosEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/ListarProdutosEstoqueResponse")]
        System.Threading.Tasks.Task<EstoqueCliente1.ServiceReference1.EstoqueData[]> ListarProdutosEstoqueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/IncluirProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/IncluirProdutoEstoqueResponse")]
        bool IncluirProdutoEstoque(EstoqueCliente1.ServiceReference1.EstoqueData Estoque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/IncluirProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/IncluirProdutoEstoqueResponse")]
        System.Threading.Tasks.Task<bool> IncluirProdutoEstoqueAsync(EstoqueCliente1.ServiceReference1.EstoqueData Estoque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/RemoverProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/RemoverProdutoEstoqueResponse")]
        bool RemoverProdutoEstoque(string NumeroProdutoEstoque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/RemoverProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/RemoverProdutoEstoqueResponse")]
        System.Threading.Tasks.Task<bool> RemoverProdutoEstoqueAsync(string NumeroProdutoEstoque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/ConsultarEstoqueResponse")]
        int ConsultarEstoque(string NumeroProdutoEstoque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/ConsultarEstoqueResponse")]
        System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string NumeroProdutoEstoque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/AdicionarQtdeProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/AdicionarQtdeProdutoEstoqueResp" +
            "onse")]
        bool AdicionarQtdeProdutoEstoque(string NumeroProdutoEstoque, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/AdicionarQtdeProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/AdicionarQtdeProdutoEstoqueResp" +
            "onse")]
        System.Threading.Tasks.Task<bool> AdicionarQtdeProdutoEstoqueAsync(string NumeroProdutoEstoque, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/RemoverQtdeProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/RemoverQtdeProdutoEstoqueRespon" +
            "se")]
        bool RemoverQtdeProdutoEstoque(string NumeroProdutoEstoque, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/RemoverQtdeProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/RemoverQtdeProdutoEstoqueRespon" +
            "se")]
        System.Threading.Tasks.Task<bool> RemoverQtdeProdutoEstoqueAsync(string NumeroProdutoEstoque, int Quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/VerProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/VerProdutoEstoqueResponse")]
        EstoqueCliente1.ServiceReference1.EstoqueData VerProdutoEstoque(string NumeroProdutoEstoque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IEstoqueService/VerProdutoEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IEstoqueService/VerProdutoEstoqueResponse")]
        System.Threading.Tasks.Task<EstoqueCliente1.ServiceReference1.EstoqueData> VerProdutoEstoqueAsync(string NumeroProdutoEstoque);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstoqueServiceChannel : EstoqueCliente1.ServiceReference1.IEstoqueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstoqueServiceClient : System.ServiceModel.ClientBase<EstoqueCliente1.ServiceReference1.IEstoqueService>, EstoqueCliente1.ServiceReference1.IEstoqueService {
        
        public EstoqueServiceClient() {
        }
        
        public EstoqueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstoqueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstoqueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstoqueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EstoqueCliente1.ServiceReference1.EstoqueData[] ListarProdutosEstoque() {
            return base.Channel.ListarProdutosEstoque();
        }
        
        public System.Threading.Tasks.Task<EstoqueCliente1.ServiceReference1.EstoqueData[]> ListarProdutosEstoqueAsync() {
            return base.Channel.ListarProdutosEstoqueAsync();
        }
        
        public bool IncluirProdutoEstoque(EstoqueCliente1.ServiceReference1.EstoqueData Estoque) {
            return base.Channel.IncluirProdutoEstoque(Estoque);
        }
        
        public System.Threading.Tasks.Task<bool> IncluirProdutoEstoqueAsync(EstoqueCliente1.ServiceReference1.EstoqueData Estoque) {
            return base.Channel.IncluirProdutoEstoqueAsync(Estoque);
        }
        
        public bool RemoverProdutoEstoque(string NumeroProdutoEstoque) {
            return base.Channel.RemoverProdutoEstoque(NumeroProdutoEstoque);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverProdutoEstoqueAsync(string NumeroProdutoEstoque) {
            return base.Channel.RemoverProdutoEstoqueAsync(NumeroProdutoEstoque);
        }
        
        public int ConsultarEstoque(string NumeroProdutoEstoque) {
            return base.Channel.ConsultarEstoque(NumeroProdutoEstoque);
        }
        
        public System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string NumeroProdutoEstoque) {
            return base.Channel.ConsultarEstoqueAsync(NumeroProdutoEstoque);
        }
        
        public bool AdicionarQtdeProdutoEstoque(string NumeroProdutoEstoque, int Quantidade) {
            return base.Channel.AdicionarQtdeProdutoEstoque(NumeroProdutoEstoque, Quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> AdicionarQtdeProdutoEstoqueAsync(string NumeroProdutoEstoque, int Quantidade) {
            return base.Channel.AdicionarQtdeProdutoEstoqueAsync(NumeroProdutoEstoque, Quantidade);
        }
        
        public bool RemoverQtdeProdutoEstoque(string NumeroProdutoEstoque, int Quantidade) {
            return base.Channel.RemoverQtdeProdutoEstoque(NumeroProdutoEstoque, Quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverQtdeProdutoEstoqueAsync(string NumeroProdutoEstoque, int Quantidade) {
            return base.Channel.RemoverQtdeProdutoEstoqueAsync(NumeroProdutoEstoque, Quantidade);
        }
        
        public EstoqueCliente1.ServiceReference1.EstoqueData VerProdutoEstoque(string NumeroProdutoEstoque) {
            return base.Channel.VerProdutoEstoque(NumeroProdutoEstoque);
        }
        
        public System.Threading.Tasks.Task<EstoqueCliente1.ServiceReference1.EstoqueData> VerProdutoEstoqueAsync(string NumeroProdutoEstoque) {
            return base.Channel.VerProdutoEstoqueAsync(NumeroProdutoEstoque);
        }
    }
}
